/**
 * Permission System Constants
 * Phase 2: RBAC Implementation
 */

// =============================================================================
// Permission Definitions
// =============================================================================

export const PERMISSIONS = {
  // ========== Organization Level ==========
  'org:read': 'View organization information',
  'org:update': 'Update organization settings',
  'org:delete': 'Delete organization',
  'org:billing': 'Manage billing',
  'org:members:read': 'View organization members',
  'org:members:invite': 'Invite members',
  'org:members:remove': 'Remove members',
  'org:members:update_role': 'Update member roles',
  'org:roles:read': 'View roles',
  'org:roles:create': 'Create roles',
  'org:roles:update': 'Update roles',
  'org:roles:delete': 'Delete roles',
  'org:audit_log': 'View audit logs',

  // ========== Workspace Level ==========
  'workspace:create': 'Create workspaces',
  'workspace:read': 'View workspaces',
  'workspace:update': 'Update workspaces',
  'workspace:delete': 'Delete workspaces',
  'workspace:members:read': 'View workspace members',
  'workspace:members:manage': 'Manage workspace members',

  // ========== Project Level ==========
  'project:create': 'Create projects',
  'project:read': 'View projects',
  'project:update': 'Update project settings',
  'project:delete': 'Delete projects',
  'project:archive': 'Archive projects',
  'project:members:read': 'View project members',
  'project:members:manage': 'Manage project members',
  'project:share': 'Share projects',
  'project:fields:read': 'View custom fields',
  'project:fields:manage': 'Manage custom fields',
  'project:views:read': 'View views',
  'project:views:manage': 'Manage views',

  // ========== Task Level ==========
  'task:create': 'Create tasks',
  'task:read': 'View tasks',
  'task:update': 'Update tasks',
  'task:delete': 'Delete tasks',
  'task:assign': 'Assign tasks',
  'task:move': 'Move tasks',
  'task:comment:read': 'View comments',
  'task:comment:create': 'Create comments',
  'task:comment:update': 'Update own comments',
  'task:comment:delete': 'Delete comments',
  'task:attachment:read': 'View attachments',
  'task:attachment:manage': 'Manage attachments',
  'task:time:read': 'View time entries',
  'task:time:manage': 'Manage time entries',

  // ========== View Level ==========
  'view:create': 'Create views',
  'view:update': 'Update views',
  'view:delete': 'Delete views',
  'view:share': 'Share views',
} as const;

export type Permission = keyof typeof PERMISSIONS;

// =============================================================================
// Permission Groups (for UI organization)
// =============================================================================

export const PERMISSION_GROUPS = {
  organization: {
    label: 'Organization',
    permissions: [
      'org:read',
      'org:update',
      'org:delete',
      'org:billing',
      'org:members:read',
      'org:members:invite',
      'org:members:remove',
      'org:members:update_role',
      'org:roles:read',
      'org:roles:create',
      'org:roles:update',
      'org:roles:delete',
      'org:audit_log',
    ],
  },
  workspace: {
    label: 'Workspace',
    permissions: [
      'workspace:create',
      'workspace:read',
      'workspace:update',
      'workspace:delete',
      'workspace:members:read',
      'workspace:members:manage',
    ],
  },
  project: {
    label: 'Project',
    permissions: [
      'project:create',
      'project:read',
      'project:update',
      'project:delete',
      'project:archive',
      'project:members:read',
      'project:members:manage',
      'project:share',
      'project:fields:read',
      'project:fields:manage',
      'project:views:read',
      'project:views:manage',
    ],
  },
  task: {
    label: 'Task',
    permissions: [
      'task:create',
      'task:read',
      'task:update',
      'task:delete',
      'task:assign',
      'task:move',
      'task:comment:read',
      'task:comment:create',
      'task:comment:update',
      'task:comment:delete',
      'task:attachment:read',
      'task:attachment:manage',
      'task:time:read',
      'task:time:manage',
    ],
  },
  view: {
    label: 'View',
    permissions: ['view:create', 'view:update', 'view:delete', 'view:share'],
  },
} as const;

// =============================================================================
// Preset Roles
// =============================================================================

export const PRESET_ROLES = {
  org_owner: {
    name: 'Organization Owner',
    slug: 'org_owner',
    description: 'Full access to all organization resources',
    permissions: Object.keys(PERMISSIONS) as Permission[],
    isSystem: true,
    hierarchyLevel: 100,
  },
  org_admin: {
    name: 'Organization Admin',
    slug: 'org_admin',
    description: 'Manage organization except deletion',
    permissions: Object.keys(PERMISSIONS).filter(
      (p) => p !== 'org:delete'
    ) as Permission[],
    isSystem: true,
    hierarchyLevel: 90,
  },
  workspace_admin: {
    name: 'Workspace Admin',
    slug: 'workspace_admin',
    description: 'Full access to workspace and projects',
    permissions: [
      'org:read',
      'org:members:read',
      'workspace:create',
      'workspace:read',
      'workspace:update',
      'workspace:delete',
      'workspace:members:read',
      'workspace:members:manage',
      'project:create',
      'project:read',
      'project:update',
      'project:delete',
      'project:archive',
      'project:members:read',
      'project:members:manage',
      'project:share',
      'project:fields:read',
      'project:fields:manage',
      'project:views:read',
      'project:views:manage',
      'task:create',
      'task:read',
      'task:update',
      'task:delete',
      'task:assign',
      'task:move',
      'task:comment:read',
      'task:comment:create',
      'task:comment:update',
      'task:comment:delete',
      'task:attachment:read',
      'task:attachment:manage',
      'task:time:read',
      'task:time:manage',
      'view:create',
      'view:update',
      'view:delete',
      'view:share',
    ] as Permission[],
    isSystem: true,
    hierarchyLevel: 70,
  },
  project_admin: {
    name: 'Project Admin',
    slug: 'project_admin',
    description: 'Full access to assigned projects',
    permissions: [
      'org:read',
      'workspace:read',
      'project:read',
      'project:update',
      'project:archive',
      'project:members:read',
      'project:members:manage',
      'project:share',
      'project:fields:read',
      'project:fields:manage',
      'project:views:read',
      'project:views:manage',
      'task:create',
      'task:read',
      'task:update',
      'task:delete',
      'task:assign',
      'task:move',
      'task:comment:read',
      'task:comment:create',
      'task:comment:update',
      'task:comment:delete',
      'task:attachment:read',
      'task:attachment:manage',
      'task:time:read',
      'task:time:manage',
      'view:create',
      'view:update',
      'view:delete',
      'view:share',
    ] as Permission[],
    isSystem: true,
    hierarchyLevel: 50,
  },
  member: {
    name: 'Member',
    slug: 'member',
    description: 'Standard member access',
    permissions: [
      'org:read',
      'org:members:read',
      'workspace:read',
      'workspace:members:read',
      'project:read',
      'project:members:read',
      'project:fields:read',
      'project:views:read',
      'task:create',
      'task:read',
      'task:update',
      'task:assign',
      'task:move',
      'task:comment:read',
      'task:comment:create',
      'task:comment:update',
      'task:attachment:read',
      'task:attachment:manage',
      'task:time:read',
      'task:time:manage',
      'view:create',
      'view:update',
    ] as Permission[],
    isSystem: true,
    hierarchyLevel: 30,
  },
  guest: {
    name: 'Guest',
    slug: 'guest',
    description: 'Read-only access',
    permissions: [
      'org:read',
      'workspace:read',
      'project:read',
      'project:fields:read',
      'project:views:read',
      'task:read',
      'task:comment:read',
      'task:attachment:read',
      'task:time:read',
    ] as Permission[],
    isSystem: true,
    hierarchyLevel: 10,
  },
} as const;

export type PresetRoleSlug = keyof typeof PRESET_ROLES;
